/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kAhnrc4yp7SieEoMyjLDJq
// Component: 3PZJu-bYfHVO

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import SidebarRal from "../../SidebarRal"; // plasmic-import: XFZUMDvK7XzJ/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { TabsContainer } from "@plasmicpkgs/plasmic-tabs";
import { TabButton } from "@plasmicpkgs/plasmic-tabs";
import Button from "../../Button"; // plasmic-import: lBHNzts6tFyj/component
import { TabUnderline } from "@plasmicpkgs/plasmic-tabs";
import { TabContent } from "@plasmicpkgs/plasmic-tabs";
import LinkPreview from "../../LinkPreview"; // plasmic-import: EA8sEmKdiXm4/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: kAhnrc4yp7SieEoMyjLDJq/projectcss
import sty from "./PlasmicHomepageExperimental.module.css"; // plasmic-import: 3PZJu-bYfHVO/css

import CheckSvgIcon from "../plasmic_tabs/icons/PlasmicIcon__CheckSvg"; // plasmic-import: zq2s7N0xWucT/icon
import IconIcon from "../plasmic_tabs/icons/PlasmicIcon__Icon"; // plasmic-import: 8K40faRNhuCj/icon

createPlasmicElementProxy;

export type PlasmicHomepageExperimental__VariantMembers = {};
export type PlasmicHomepageExperimental__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepageExperimental__VariantsArgs;
export const PlasmicHomepageExperimental__VariantProps =
  new Array<VariantPropType>();

export type PlasmicHomepageExperimental__ArgsType = {};
type ArgPropType = keyof PlasmicHomepageExperimental__ArgsType;
export const PlasmicHomepageExperimental__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepageExperimental__OverridesType = {
  root?: Flex__<"div">;
  sidebarRal?: Flex__<typeof SidebarRal>;
  header?: Flex__<"section">;
  headerAnimationSlot?: Flex__<typeof Reveal>;
  welcomeText?: Flex__<"div">;
  weatherEmbed?: Flex__<typeof Embed>;
  appsSection?: Flex__<"section">;
  appGrid?: Flex__<"div">;
  column1?: Flex__<"div">;
  column2?: Flex__<"div">;
  column3?: Flex__<"div">;
  column4?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  column5?: Flex__<"div">;
  column6?: Flex__<"div">;
  tabsContainer?: Flex__<typeof TabsContainer>;
  tabUnderline?: Flex__<typeof TabUnderline>;
  linkPreview?: Flex__<typeof LinkPreview>;
};

export interface DefaultHomepageExperimentalProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepageExperimental__RenderFunc(props: {
  variants: PlasmicHomepageExperimental__VariantsArgs;
  args: PlasmicHomepageExperimental__ArgsType;
  overrides: PlasmicHomepageExperimental__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicHomepageExperimental.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepageExperimental.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepageExperimental.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <SidebarRal
            data-plasmic-name={"sidebarRal"}
            data-plasmic-override={overrides.sidebarRal}
            className={classNames("__wab_instance", sty.sidebarRal)}
          />

          <section
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <Reveal
              data-plasmic-name={"headerAnimationSlot"}
              data-plasmic-override={overrides.headerAnimationSlot}
              cascade={true}
              className={classNames("__wab_instance", sty.headerAnimationSlot)}
              damping={-0.1}
              direction={"down"}
              duration={1100}
              effect={"bounce"}
              triggerOnce={true}
            >
              <div
                data-plasmic-name={"welcomeText"}
                data-plasmic-override={overrides.welcomeText}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.welcomeText
                )}
              >
                {"Welcome Sophia!"}
              </div>
              <Embed
                data-plasmic-name={"weatherEmbed"}
                data-plasmic-override={overrides.weatherEmbed}
                className={classNames("__wab_instance", sty.weatherEmbed)}
                code={
                  '<a class="weatherwidget-io" href="https://forecast7.com/en/44d85n93d47/eden-prairie/?unit=us" data-label_1="Eden Prairie" data-label_2="Weather" data-font="Arial Rounded MT Bold" data-icons="Climacons Animated" data-theme="pure" data-basecolor="" data-shadow="rgba(0, 0, 0, 0.38)" data-textcolor="#ffffff" data-highcolor="#f37878" data-lowcolor="#4ea6e5" data-suncolor="#fdc526" data-raincolor="#537aff" data-snowcolor="#5afafa" >EDEN PRAIRIE Weather</a>\n<script>\n!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=\'https://weatherwidget.io/js/widget.min.js\';fjs.parentNode.insertBefore(js,fjs);}}(document,\'script\',\'weatherwidget-io-js\');\n</script>'
                }
              />
            </Reveal>
          </section>
          <section
            data-plasmic-name={"appsSection"}
            data-plasmic-override={overrides.appsSection}
            className={classNames(projectcss.all, sty.appsSection)}
          >
            <div
              data-plasmic-name={"appGrid"}
              data-plasmic-override={overrides.appGrid}
              className={classNames(projectcss.all, sty.appGrid)}
            >
              <div
                data-plasmic-name={"column1"}
                data-plasmic-override={overrides.column1}
                className={classNames(projectcss.all, sty.column1)}
              />

              <div
                data-plasmic-name={"column2"}
                data-plasmic-override={overrides.column2}
                className={classNames(projectcss.all, sty.column2)}
              />

              <div
                data-plasmic-name={"column3"}
                data-plasmic-override={overrides.column3}
                className={classNames(projectcss.all, sty.column3)}
              />

              <div
                data-plasmic-name={"column4"}
                data-plasmic-override={overrides.column4}
                className={classNames(projectcss.all, sty.column4)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__p2N7L)}
                  displayHeight={"201px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sophias_home/images/eSportsGraphicsSquare6Png.png",
                    fullWidth: 960,
                    fullHeight: 960,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicLink__
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(projectcss.all, projectcss.a, sty.link)}
                  component={Link}
                  href={`/games`}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__zJpSp)}
                    displayHeight={"201px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/sophias_home/images/_3De91E38Efc64867A2855D7B1A09F896Jpg.jpg",
                      fullWidth: 200,
                      fullHeight: 200,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
              </div>
              <div
                data-plasmic-name={"column5"}
                data-plasmic-override={overrides.column5}
                className={classNames(projectcss.all, sty.column5)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mhCma)}
                  displayHeight={"201px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sophias_home/images/eSportsGraphicsSquare6Png.png",
                    fullWidth: 960,
                    fullHeight: 960,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div
                data-plasmic-name={"column6"}
                data-plasmic-override={overrides.column6}
                className={classNames(projectcss.all, sty.column6)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__m0OeH)}
                  displayHeight={"201px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/sophias_home/images/eSportsGraphicsSquare6Png.png",
                    fullWidth: 960,
                    fullHeight: 960,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </section>
          <TabsContainer
            data-plasmic-name={"tabsContainer"}
            data-plasmic-override={overrides.tabsContainer}
            initialKey={"tab1"}
          >
            <DataCtxReader__>
              {$ctx => (
                <div className={classNames(projectcss.all, sty.freeBox__q9Oy6)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__r04Ze)}
                  >
                    <TabButton
                      className={classNames(
                        "__wab_instance",
                        sty.tabButton__cJdDo
                      )}
                      tabKey={"tab1"}
                    >
                      <Button>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xqJw9
                          )}
                        >
                          {"Tab 1"}
                        </div>
                      </Button>
                    </TabButton>
                    <TabButton
                      className={classNames(
                        "__wab_instance",
                        sty.tabButton__psGTr
                      )}
                      tabKey={"tab2"}
                    >
                      <Button>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__f6Jb
                          )}
                        >
                          {"Tab 2"}
                        </div>
                      </Button>
                    </TabButton>
                    <TabUnderline
                      data-plasmic-name={"tabUnderline"}
                      data-plasmic-override={overrides.tabUnderline}
                      className={classNames("__wab_instance", sty.tabUnderline)}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cfWvq)}
                  >
                    <TabContent
                      className={classNames(
                        "__wab_instance",
                        sty.tabContent__dK8Zp
                      )}
                      tabKey={"tab1"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kTkDk
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ykIpP
                          )}
                        >
                          {"Some content for tab 1"}
                        </div>
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__h2BLp)}
                          displayHeight={"201px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/sophias_home/images/eSportsGraphicsSquare6Png.png",
                            fullWidth: 960,
                            fullHeight: 960,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </TabContent>
                    <TabContent
                      className={classNames(
                        "__wab_instance",
                        sty.tabContent__vKxaN
                      )}
                      tabKey={"tab2"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__abYra
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wqGPe
                          )}
                        >
                          {"Some content for tab 2"}
                        </div>
                      </div>
                    </TabContent>
                  </div>
                </div>
              )}
            </DataCtxReader__>
          </TabsContainer>
          <LinkPreview
            data-plasmic-name={"linkPreview"}
            data-plasmic-override={overrides.linkPreview}
            className={classNames("__wab_instance", sty.linkPreview)}
            url={"https://wearescrewd.com/"}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "sidebarRal",
    "header",
    "headerAnimationSlot",
    "welcomeText",
    "weatherEmbed",
    "appsSection",
    "appGrid",
    "column1",
    "column2",
    "column3",
    "column4",
    "link",
    "column5",
    "column6",
    "tabsContainer",
    "tabUnderline",
    "linkPreview"
  ],
  sidebarRal: ["sidebarRal"],
  header: ["header", "headerAnimationSlot", "welcomeText", "weatherEmbed"],
  headerAnimationSlot: ["headerAnimationSlot", "welcomeText", "weatherEmbed"],
  welcomeText: ["welcomeText"],
  weatherEmbed: ["weatherEmbed"],
  appsSection: [
    "appsSection",
    "appGrid",
    "column1",
    "column2",
    "column3",
    "column4",
    "link",
    "column5",
    "column6"
  ],
  appGrid: [
    "appGrid",
    "column1",
    "column2",
    "column3",
    "column4",
    "link",
    "column5",
    "column6"
  ],
  column1: ["column1"],
  column2: ["column2"],
  column3: ["column3"],
  column4: ["column4", "link"],
  link: ["link"],
  column5: ["column5"],
  column6: ["column6"],
  tabsContainer: ["tabsContainer", "tabUnderline"],
  tabUnderline: ["tabUnderline"],
  linkPreview: ["linkPreview"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  sidebarRal: typeof SidebarRal;
  header: "section";
  headerAnimationSlot: typeof Reveal;
  welcomeText: "div";
  weatherEmbed: typeof Embed;
  appsSection: "section";
  appGrid: "div";
  column1: "div";
  column2: "div";
  column3: "div";
  column4: "div";
  link: "a";
  column5: "div";
  column6: "div";
  tabsContainer: typeof TabsContainer;
  tabUnderline: typeof TabUnderline;
  linkPreview: typeof LinkPreview;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepageExperimental__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepageExperimental__VariantsArgs;
    args?: PlasmicHomepageExperimental__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepageExperimental__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepageExperimental__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepageExperimental__ArgProps,
          internalVariantPropNames: PlasmicHomepageExperimental__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepageExperimental__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepageExperimental";
  } else {
    func.displayName = `PlasmicHomepageExperimental.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepageExperimental = Object.assign(
  // Top-level PlasmicHomepageExperimental renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sidebarRal: makeNodeComponent("sidebarRal"),
    header: makeNodeComponent("header"),
    headerAnimationSlot: makeNodeComponent("headerAnimationSlot"),
    welcomeText: makeNodeComponent("welcomeText"),
    weatherEmbed: makeNodeComponent("weatherEmbed"),
    appsSection: makeNodeComponent("appsSection"),
    appGrid: makeNodeComponent("appGrid"),
    column1: makeNodeComponent("column1"),
    column2: makeNodeComponent("column2"),
    column3: makeNodeComponent("column3"),
    column4: makeNodeComponent("column4"),
    link: makeNodeComponent("link"),
    column5: makeNodeComponent("column5"),
    column6: makeNodeComponent("column6"),
    tabsContainer: makeNodeComponent("tabsContainer"),
    tabUnderline: makeNodeComponent("tabUnderline"),
    linkPreview: makeNodeComponent("linkPreview"),

    // Metadata about props expected for PlasmicHomepageExperimental
    internalVariantProps: PlasmicHomepageExperimental__VariantProps,
    internalArgProps: PlasmicHomepageExperimental__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Sophia's Home 6",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepageExperimental;
/* prettier-ignore-end */
